// JSON Schema type (subset used for tool parameters)
export type JSONSchema = Record<string, unknown>;

// --- Tool Types ---

/**
 * Passed to every tool handler as its second argument. Handlers written
 * against older versions take one argument, so read it as `context?.signal`.
 */
export interface ToolContext {
  /** Aborts when the interaction is cancelled. Forward it to fetch or other long work. */
  signal?: AbortSignal;
}

export type ToolHandler<TArgs = unknown> = (
  args: TArgs,
  context?: ToolContext,
) => unknown | Promise<unknown>;

// --- Standard Schema ---

/**
 * A minimal copy of the Standard Schema v1 interface (standardschema.dev).
 * The spec is meant to be copied, which keeps this package dependency free
 * while accepting validators from Zod 3.24+, Valibot 1+ and ArkType 2+.
 */
export interface StandardSchemaV1<Input = unknown, Output = Input> {
  readonly '~standard': StandardSchemaProps<Input, Output>;
}

export interface StandardSchemaProps<Input = unknown, Output = Input> {
  readonly version: 1;
  readonly vendor: string;
  readonly validate: (
    value: unknown,
  ) => StandardSchemaResult<Output> | Promise<StandardSchemaResult<Output>>;
  readonly types?:
    | { readonly input: Input; readonly output: Output }
    | undefined;
}

export type StandardSchemaResult<Output> =
  | { readonly value: Output; readonly issues?: undefined }
  | { readonly issues: ReadonlyArray<StandardSchemaIssue> };

export interface StandardSchemaIssue {
  readonly message: string;
  readonly path?:
    | ReadonlyArray<PropertyKey | { readonly key: PropertyKey }>
    | undefined;
}

/** The value a schema produces after validation, which transforms may reshape. */
export type InferSchemaOutput<S extends StandardSchemaV1> = NonNullable<
  S['~standard']['types']
>['output'];

export interface ToolOptions {
  description?: string;
  parameters?: JSONSchema;
  /**
   * Optional Standard Schema validator (Zod 3.24+, Valibot 1+, ArkType 2+).
   * When present, runtime validation runs through it instead of the built-in
   * JSON Schema subset, and the handler receives the validated value.
   * `parameters` still supplies the JSON Schema the model sees.
   */
  schema?: StandardSchemaV1;
  confirm?: boolean;
}

export interface ToolDefinition<TArgs = unknown> {
  name: string;
  handler: ToolHandler<TArgs>;
  description?: string;
  parameters?: JSONSchema;
  schema?: StandardSchemaV1;
  confirm: boolean;
}

/**
 * A tool definition with its argument type erased. Tools registered with
 * different argument types can only share one array through this type, since
 * handler parameters are contravariant.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AnyToolDefinition = ToolDefinition<any>;

// --- Conversation Types ---

export type ToolCallStatus =
  | 'success'
  | 'error'
  | 'denied'
  | 'confirmed'
  | 'cancelled';

export interface ToolCallResult {
  toolName: string;
  args: unknown;
  result: unknown;
  status: ToolCallStatus;
}

export interface ConversationEntry {
  role: 'user' | 'assistant' | 'tool';
  content: string;
  toolCalls?: ToolCallResult[];
  /** Assistant entries only: the interaction ended with this error, ABORTED included. */
  error?: AgentError;
  timestamp: number;
}

// --- Events ---

/** Observation only. Emitted through `AgentOptions.onEvent` as the loop runs. */
export type AgentEvent =
  | { type: 'turn_start'; turn: number; maxTurns: number }
  | { type: 'state_read'; requested: string[]; keys: string[] }
  | { type: 'tool_start'; toolName: string; args: unknown }
  | {
      type: 'tool_end';
      toolName: string;
      args: unknown;
      result: unknown;
      status: ToolCallStatus;
    };

// --- Agent Response ---

export type AgentErrorCode =
  | 'ABORTED'
  | 'MAX_TURNS'
  | 'ADAPTER_ERROR'
  | 'TRUNCATED'
  | 'REFUSED';

export interface AgentError {
  message: string;
  code?: AgentErrorCode;
  /** HTTP status when the failure came from an adapter with one. */
  status?: number;
  cause?: unknown;
}

export interface TokenUsage {
  /** Total input tokens for the call, cached portion included. */
  promptTokens: number;
  /** Output tokens generated by the model. */
  completionTokens: number;
  /** Part of `promptTokens` served from the cache, when the provider reports it. */
  cacheReadTokens?: number;
  /** Part of `promptTokens` written to the cache, when the provider reports it. */
  cacheWriteTokens?: number;
}

export interface AgentResponse {
  message: string;
  toolCalls: ToolCallResult[];
  error?: AgentError;
  /** Totalled across every model call in the interaction, when the adapter reports it. */
  usage?: TokenUsage;
}

// --- Agent Context (useAgent return type) ---

export interface SendOptions {
  /** Cancels the interaction. The pending response resolves with an ABORTED error. */
  signal?: AbortSignal;
}

export interface AgentContext {
  send: (message: string, options?: SendOptions) => Promise<AgentResponse>;
  isProcessing: boolean;
  history: ConversationEntry[];
  clearHistory: () => void;
  lastResponse: AgentResponse | null;
}

// --- Permissions ---

export interface PermissionsConfig {
  canAccess: string[];
  canExecute: string[];
  stateDescriptions?: Record<string, string>;
}

// --- Model Adapter ---

export interface ConversationMessage {
  role: 'user' | 'assistant' | 'tool';
  content: string;
  toolCallId?: string;
  toolCalls?: LLMToolCall[];
  /** Tool messages only: the result reports a failure (denied, invalid arguments, handler threw). */
  isError?: boolean;
  /** Opaque, adapter-owned. The loop copies it from ModelResponse and replays it verbatim. */
  providerData?: unknown;
}

export interface LLMToolDefinition {
  name: string;
  description: string;
  parameters: JSONSchema;
}

export interface LLMToolCall {
  id: string;
  name: string;
  arguments: unknown;
}

export interface ModelRequest {
  messages: ConversationMessage[];
  tools: LLMToolDefinition[];
  state: Record<string, unknown>;
  systemPrompt?: string;
  stateManifest?: { key: string; description: string }[];
  /** Adapters should forward this to their transport so requests cancel in flight. */
  signal?: AbortSignal;
}

/** Why the model stopped, normalized across providers. */
export type StopReason =
  | 'end'
  | 'tool_use'
  | 'max_tokens'
  | 'refusal'
  | 'other';

export interface ModelResponse {
  content: string | null;
  toolCalls?: LLMToolCall[];
  usage?: TokenUsage;
  stopReason?: StopReason;
  providerData?: unknown;
}

export interface ModelAdapter {
  sendMessage(request: ModelRequest): Promise<ModelResponse>;
}

// --- Provider Props ---

/**
 * Application state, as an object read on each access or a getter called on
 * each access. Any object shape is accepted: store interfaces rarely carry the
 * index signature that `Record<string, unknown>` would demand.
 */
export type StateSource = object | (() => object);

export interface PendingToolCall {
  toolName: string;
  args: unknown;
  description?: string;
  /** Aborts when the interaction is cancelled while confirmation is pending. */
  signal?: AbortSignal;
}

export interface ToolCallEvent {
  toolName: string;
  args: unknown;
  result: unknown;
  status: ToolCallStatus;
}

export interface AgentOptions {
  debug?: boolean;
  maxTurns?: number;
  systemPrompt?: string;
  /** Byte ceiling per state key in a snapshot. Unset means no limit. */
  maxStateBytes?: number;
  onError?: (error: AgentError) => void;
  onToolCall?: (call: ToolCallEvent) => void;
  onConfirm?: (call: PendingToolCall) => Promise<boolean>;
  onEvent?: (event: AgentEvent) => void;
}

export interface AIAgentProviderProps {
  model: ModelAdapter;
  state: StateSource;
  tools: AnyToolDefinition[];
  permissions: PermissionsConfig;
  options?: AgentOptions;
  children: React.ReactNode;
}

// --- Adapter Config ---

export interface OpenAIAdapterConfig {
  apiKey?: string;
  model?: string;
  baseURL?: string;
  /** Defaults to 0.2. Pass null to omit the field from the request. */
  temperature?: number | null;
  headers?: Record<string, string>;
}

export interface ClaudeAdapterConfig {
  apiKey?: string;
  model?: string;
  baseURL?: string;
  /** Required by the Anthropic API. Defaults to 16000. */
  maxTokens?: number;
  /** Prompt caching for tools and system prompt. Defaults to true. */
  cache?: boolean;
  headers?: Record<string, string>;
}
